buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath "io.freefair.gradle:lombok-plugin:8.6"
    }
}
subprojects {
    apply plugin: 'java'
    apply plugin: 'io.freefair.lombok'
    repositories {
        mavenCentral()
    }
dependencies {
}
}