plugins {
    id 'java'
}

group = 'org.example'

repositories {
    mavenCentral()
}

dependencies {

    implementation 'io.rest-assured:rest-assured:5.1.1'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.14.0'
    implementation 'ch.qos.logback:logback-classic:1.5.10'
    implementation 'ch.qos.logback:logback-core:1.5.10'

    annotationProcessor 'org.projectlombok:lombok:1.18.30'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'

    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter-api")
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.9.3'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.14.0'
    testImplementation 'org.hamcrest:hamcrest:2.2'
    testImplementation 'com.fasterxml.jackson.core:jackson-core:2.14.0'
    testImplementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.15.3'
    testImplementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.15.3'

    implementation 'org.projectlombok:lombok:1.18.30'
    implementation 'org.slf4j:slf4j-api:2.0.10'
    implementation 'org.projectlombok:lombok:1.18.30'
}

test {
    useJUnitPlatform()
    testLogging {
        events "PASSED", "FAILED", "SKIPPED"
        showStandardStreams = true
        exceptionFormat = 'full'
    }

    test.outputs.upToDateWhen { false }

}